In [1]:
import numpy as np

In [2]:
# create arrays
arr1 = [3, 4, 5, 6, 7]
print (type(arr1))

<class 'list'>


In [3]:
# list
print (arr1)

[3, 4, 5, 6, 7]


In [4]:
# pinakas
narr1 = np.array(arr1)
print(type(narr1))

<class 'numpy.ndarray'>


In [6]:
# multi d arrays
arr2=[[1,2,3,4],[5,6,7,8]]
print (type(arr2))

<class 'list'>


In [7]:
# list
print(arr2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [8]:
# pinakas
narr2=np.array(arr2)
print(type(narr2))

<class 'numpy.ndarray'>


In [9]:
print(narr2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arr3=[[1,2,3,4],[5,6,7,8],[9,8,7,6]]
narr3=np.array(arr3)
print(narr3)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


In [12]:
# shape = dimensions tou pinaka
print(narr3.shape)

(3, 4)


In [15]:
# 2x2 with 0s
zer1=np.zeros((2,2))
print(zer1)

[[0. 0.]
 [0. 0.]]


In [16]:
print(type(zer1))

<class 'numpy.ndarray'>


In [18]:
# 3x4 arrays with 5s
full=np.full((3,4),5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
# 4x4 diagonal with 1s. Prosoxi den katalabainei an einai tetragonikos pinakas
eye1=np.eye(3,3)
print(eye1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
