In [1]:
import numpy as np

In [2]:
a=[1,2,11,6,8,18,2]
na=np.array(a)
print(na)

[ 1  2 11  6  8 18  2]


In [3]:
print(type(na)) #print na type

<class 'numpy.ndarray'>


In [4]:
print(na.shape) #dimensions

(7,)


In [8]:
print(na[3]) # element with index=3

6


In [9]:
print(na[1:5]) # elements from index=1 to index=5-1

[ 2 11  6  8]


In [10]:
print(na[2:]) #elements from index=2 till the end

[11  6  8 18  2]


In [11]:
print(na[1:5:2]) #elements from index=1 to index=5-1 with a step of 2

[2 6]


In [12]:
print(na[1:11:2]) # de mas noiazei to 11, apla paei mexri telous

[ 2  6 18]


In [14]:
print(na[1:11:10]) # de mas noiazei to 11,oute to vima 10 apla paei mexri telous kai pairnei to proto stoixeio

[2]


In [15]:
print(na[-7]) #negative index

1


In [16]:
print(na[-7:-2]) #negative index. From index=-7 to index=-2-1

[ 1  2 11  6  8]


In [17]:
print(na[:4]) #elements from beginning to index=4-1

[ 1  2 11  6]


In [18]:
b=na[:] #copy of all array 
print(b)

[ 1  2 11  6  8 18  2]


In [21]:
x=np.array([2,6,8,4]) #concatenate 2 arrays
y=np.array([11,8,2])
z=np.concatenate([x,y])
print(z)

[ 2  6  8  4 11  8  2]


In [26]:
#convert arrays into numpy array
arr=[[1,2,3,4],[3,4,5,6],[12,7,10,9],[2,11,8,10]]   
narr=np.array(arr)
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [27]:
print(narr.shape)

(4, 4)


In [28]:
print(narr[0])  #print first row or narr array

[1 2 3 4]


In [29]:
print(narr[2,3]) #print element in row-index=2, column-index=3

9


In [33]:
print(narr[1:4,2:4]) # print array with rows:index=1 to index=4-1, collumns:index=2 to index=4-1

[[ 5  6]
 [10  9]
 [ 8 10]]


In [34]:
print(type(narr))

<class 'numpy.ndarray'>


In [35]:
narr[3,0]=14
print(narr) #replace element in row-index=3, column-index=0

[[ 1  2  3  4]
 [ 3  4  5  6]
 [12  7 10  9]
 [14 11  8 10]]


In [41]:
a=np.array([[1,2],[3,4]]) #concatenate row-column wise
b=np.array([[5,6]])
c=np.concatenate([a,b])
print(c)

[[1 2]
 [3 4]
 [5 6]]
