In [2]:
import numpy as np

In [3]:
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]
narr=np.array(arr)
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [4]:
print(narr.shape)

(5, 4)


In [5]:
narr.sum() #sum all values of the array

127

In [6]:
narr.sum(axis=0) #sum all first column (with axis=0)

array([25, 32, 35, 35])

In [7]:
narr.sum(axis=1) #sum all first row (with axis=1)

array([10, 18, 30, 38, 31])

In [8]:
narr.mean() #mesi timi

6.35

In [10]:
narr.mean(axis=0) # mean of first column (axis=0)

array([5. , 6.4, 7. , 7. ])

In [13]:
np.median(narr,axis=1) # mesos. Prosoxi, kaleitai diaforetika apo mesi timi

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [14]:
np.std(narr) #standard deviation

3.182373328193912

In [15]:
np.percentile(narr,50,axis=1) #50th percentile

array([2.5, 4.5, 7.5, 9.5, 9. ])